### ISSUE TITLE
APIM Template

### ISSUE THREAD

**Issue by hartou** [microsoft/App-Templates#3]
Team, 
I would like to know if we can have a APIM template. 
APIM (with SOAP to Rest API deployment)
APIM with the following attached services: 
- Ap Insights (Azure Monitor)
-  AAD 
Thank you
Julien LECADOU

**Comment by aarthiem** [comment]
@hartou - Please refer to the APIM+ACA app template https://github.com/Azure-Samples/app-templates-microservices-integration
